<?php
// Core Helper Functions
function redirect($url) { header("Location: $url"); exit; }
function e($str) { return htmlspecialchars($str ?? '', ENT_QUOTES, 'UTF-8'); }
function csrfToken() { if (empty($_SESSION['csrf_token'])) { $_SESSION['csrf_token'] = bin2hex(random_bytes(32)); } return $_SESSION['csrf_token']; }
function verifyCsrf($token) { return isset($_SESSION['csrf_token']) && hash_equals($_SESSION['csrf_token'], $token); }
function flash($type, $msg) { $_SESSION['flash'] = ['type' => $type, 'msg' => $msg]; }
function getFlash() { if (!empty($_SESSION['flash'])) { $f = $_SESSION['flash']; unset($_SESSION['flash']); return $f; } return null; }
function renderFlash() { $f = getFlash(); if (!$f) return ''; $icons = ['success' => '✓', 'error' => '✕', 'info' => 'ℹ']; $icon = $icons[$f['type']] ?? 'ℹ'; return '<div class="flash flash-' . e($f['type']) . '"><span class="flash-icon">' . $icon . '</span>' . e($f['msg']) . '</div>'; }
function isLoggedIn() { return isset($_SESSION['user_id']) && $_SESSION['user_id']; }
function calcBMI($w, $h) { if ($h <= 0) return 0; $h = $h / 100; return round($w / ($h * $h), 1); }
function bmiCategory($bmi) { if ($bmi < 18.5) return ['Underweight', 'info']; if ($bmi < 25) return ['Normal', 'success']; if ($bmi < 30) return ['Overweight', 'warning']; return ['Obese', 'danger']; }
function calcBMR($w, $h, $age, $gender) { $bmr = 10 * $w + 6.25 * $h - 5 * $age; return $gender === 'male' ? $bmr + 5 : $bmr - 161; }
function activityMultiplier($level) { $map = ['sedentary'=>1.2,'light'=>1.375,'moderate'=>1.55,'active'=>1.725,'very_active'=>1.9]; return $map[$level] ?? 1.55; }
function calcCalorieGoal($bmr, $activity, $goal_mode) { $tdee = $bmr * activityMultiplier($activity); $adjust = ['lose'=>-500,'maintain'=>0,'gain'=>300]; return round($tdee + ($adjust[$goal_mode] ?? 0)); }
function calcMacros($cal_goal, $goal_w, $goal_mode) { $protein_per_kg = ['lose'=>1.8,'maintain'=>1.6,'gain'=>2.0]; $p = round($goal_w * ($protein_per_kg[$goal_mode] ?? 1.6)); $f = round($cal_goal * 0.27 / 9); $c = round(($cal_goal - ($p*4) - ($f*9)) / 4); return ['protein'=>$p,'carbs'=>$c,'fats'=>$f]; }
function getTodayTotals($conn, $user_id, $date = null) { $date = $date ?? date('Y-m-d'); $stmt = $conn->prepare("SELECT COALESCE(SUM(calories),0) cal, COALESCE(SUM(protein),0) pro, COALESCE(SUM(carbs),0) carbs, COALESCE(SUM(fats),0) fats FROM meal_log WHERE user_id=? AND log_date=?"); $stmt->bind_param('is', $user_id, $date); $stmt->execute(); return $stmt->get_result()->fetch_assoc(); }
function getWaterLog($conn, $user_id, $date = null) { $date = $date ?? date('Y-m-d'); $stmt = $conn->prepare("SELECT glasses FROM water_log WHERE user_id=? AND log_date=?"); $stmt->bind_param('is', $user_id, $date); $stmt->execute(); $row = $stmt->get_result()->fetch_assoc(); return $row ? (int)$row['glasses'] : 0; }
function getWeeklyCalories($conn, $user_id) { $data = []; for ($i=6; $i>=0; $i--) { $date = date('Y-m-d', strtotime("-$i days")); $stmt = $conn->prepare("SELECT COALESCE(SUM(calories),0) total FROM meal_log WHERE user_id=? AND log_date=?"); $stmt->bind_param('is', $user_id, $date); $stmt->execute(); $row = $stmt->get_result()->fetch_assoc(); $data[] = ['date'=>$date, 'day'=>date('D',strtotime($date)), 'calories'=>(int)$row['total']]; } return $data; }
function updateStreak($user_id) { $conn = getDB(); $today = date('Y-m-d'); $stmt = $conn->prepare("SELECT current_streak, longest_streak, last_log_date FROM user_profiles WHERE user_id=?"); $stmt->bind_param('i', $user_id); $stmt->execute(); $p = $stmt->get_result()->fetch_assoc(); if (!$p) return; if ($p['last_log_date'] == $today) return; $yesterday = date('Y-m-d', strtotime('-1 day')); $newStreak = ($p['last_log_date'] == $yesterday) ? ($p['current_streak'] + 1) : 1; $longest = max($p['longest_streak'], $newStreak); $up = $conn->prepare("UPDATE user_profiles SET current_streak=?, longest_streak=?, last_log_date=? WHERE user_id=?"); $up->bind_param('iisi', $newStreak, $longest, $today, $user_id); $up->execute(); }
function checkAchievements($user_id, $streak=0) { $conn = getDB(); $badges = []; if ($streak>=7) $badges[]='streak_7'; if ($streak>=10) $badges[]='streak_10'; if ($streak>=30) $badges[]='streak_30'; $st = $conn->prepare("SELECT COUNT(*) cnt FROM meal_log WHERE user_id=?"); $st->bind_param('i', $user_id); $st->execute(); $cnt = (int)$st->get_result()->fetch_assoc()['cnt']; if ($cnt>=1) $badges[]='first_log'; if ($cnt>=10) $badges[]='logged_10_meals'; if ($cnt>=50) $badges[]='logged_50_meals'; if ($cnt>=100) $badges[]='logged_100_meals'; foreach($badges as $b) { $st2 = $conn->prepare("INSERT IGNORE INTO achievements (user_id, badge_key) VALUES (?,?)"); $st2->bind_param('is', $user_id, $b); $st2->execute(); } }
function badgeInfo($key) { $badges = ['first_log'=>['🍽️','First Bite','Logged your first meal'],'streak_7'=>['🔥','7-Day Streak','Logged meals 7 days in a row'],'streak_10'=>['⚡','10-Day Streak','Logged meals 10 days in a row'],'streak_30'=>['🏆','30-Day Streak','Logged meals 30 days in a row'],'logged_10_meals'=>['📋','Meal Tracker','Logged 10 total meals'],'logged_50_meals'=>['🥗','Nutrition Pro','Logged 50 total meals'],'logged_100_meals'=>['💪','Century Club','Logged 100 total meals']]; return $badges[$key] ?? ['🎖️', ucfirst(str_replace('_',' ',$key)), '']; }
function uploadImage($file, $dir, $max_size=5242880) { $allowed = ['image/jpeg','image/png','image/webp','image/jpg']; if (!in_array($file['type'], $allowed)) return ['error'=>'Only JPG, PNG, WebP allowed']; if ($file['size'] > $max_size) return ['error'=>'File too large']; if (!file_exists($dir)) mkdir($dir, 0777, true); $ext = strtolower(pathinfo($file['name'], PATHINFO_EXTENSION)); $name = uniqid('img_', true) . '.' . $ext; if (!move_uploaded_file($file['tmp_name'], $dir . $name)) return ['error'=>'Upload failed']; return ['name'=>$name]; }
?>